# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Match date')),
                ('home_win', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Home team win')),
                ('draw', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Draw')),
                ('visiting_win', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Visiting team win')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='times.Team', verbose_name='Home team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.League', verbose_name='League')),
                ('visiting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team', to='times.Team', verbose_name='Visiting team')),
            ],
        ),
    ]
