# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('country', models.CharField(max_length=126, verbose_name='Country')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('stadium', models.CharField(blank=True, max_length=254, verbose_name='Stadium')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('leagues', models.ManyToManyField(blank=True, to='times.League', verbose_name='League')),
            ],
        ),
    ]
