# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=126, verbose_name='Code')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Value')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.Match', verbose_name='Match')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
