# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0002_bet_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_group', to='apostas.BetGroup', verbose_name='Bet group'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='partidas.Match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='betgroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
